services:
  komplain:
    build:
      context: https://github.com/tech-masterload8/komplain-transaksi.git#main
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_PATH: /komplain
    image: komplain-transaksi:latest
    container_name: komplain-transaksi
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: "3001"
      NEXT_PUBLIC_BASE_PATH: /komplain
      ALLOW_DEV_LOGIN: "false"
    volumes:
      - komplain_uploads:/app/public/uploads

volumes:
  komplain_uploads:
